/**This class is automatically generated by LayaAirIDE, please do not make any modifications. */


/**
 * view/home/home.ls
 */
export class homeViewBase extends Laya.Scene {
    public img!: Laya.GImage;
}

