/**This class is automatically generated by LayaAirIDE, please do not make any modifications. */


/**
 * view/loading/loading.lh
 */
export class loadingBase extends Laya.GWidget {
    public img_bg!: Laya.GImage;
    public img_1!: Laya.GImage;
    public bar!: Laya.GProgressBar;
    public txt_version!: Laya.GTextField;
}

