/**This class is automatically generated by LayaAirIDE, please do not make any modifications. */


/**
 * scene/loading.ls
 */
export class loadingBase extends Laya.Scene {
    public img!: Laya.GImage;
    public btn_change!: Laya.GButton;
}

