/** auto generated by tools/genUI.js */
export class UIDefine {
    static readonly loading = "view/loading/loading.lh";
    static readonly home = "view/home/home.ls";
    static readonly mapDemo = "view/map/mapDemo.ls";
}
