/**
 * 扫描 assets/view/ 下所有 .lh 文件，生成 src/patch/UIDefine.ts
 *
 * 用法:
 *   import { genUIDefine } from "./genUIDefine.js";
 *   genUIDefine();                          // 使用默认路径
 *   genUIDefine({ viewDir: "assets/view" }); // 自定义参数
 *
 * 直接运行: node tools/genUIDefine.js
 */

import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const projectPath = path.join(__dirname, "..");

/**
 * 递归扫描目录，返回所有匹配扩展名的文件路径（相对 baseDir）
 */
function scanFiles(dir, ext, baseDir = dir) {
    const results = [];
    if (!fs.existsSync(dir)) return results;

    const entries = fs.readdirSync(dir, { withFileTypes: true });

    for (const entry of entries) {
        const fullPath = path.join(dir, entry.name);
        if (entry.isDirectory()) {
            results.push(...scanFiles(fullPath, ext, baseDir));
        } else if (entry.name.endsWith(ext)) {
            results.push(path.relative(baseDir, fullPath).replace(/\\/g, "/"));
        }
    }

    return results;
}

/**
 * 获取文件名（不含扩展名）
 * view/loading/loading.lh → loading
 * view/dialog/confirm.lh → confirm
 */
function fileName(filePath) {
    const name = filePath.split("/").pop();
    return name.replace(/\.lh$/, "");
}

/**
 * 获取文件夹名
 * view/loading/loading.lh → loading
 * view/dialog/confirm.lh → dialog
 */
function folderName(filePath) {
    const parts = filePath.split("/");
    return parts.length >= 2 ? parts[parts.length - 2] : "";
}

/**
 * 计算属性名，重名时用 文件夹_文件名 兜底
 */
function resolvePropNames(filePaths) {
    // 第一轮：优先用文件名
    const names = filePaths.map(f => ({ file: f, name: fileName(f) }));

    // 检测重名
    const count = {};
    for (const { name } of names) {
        count[name] = (count[name] || 0) + 1;
    }

    // 重名的改用 文件夹_文件名
    return names.map(({ file, name }) => {
        if (count[name] > 1) {
            return `${folderName(file)}_${name}`;
        }
        return name;
    });
}

/**
 * 生成 UIDefine.ts
 * @param {Object} [opts]
 * @param {string} [opts.viewDir]    - view 目录路径（默认 "assets/view"）
 * @param {string} [opts.outputFile] - 输出文件路径（默认 "src/patch/UIDefine.ts"）
 * @param {string} [opts.projectPath] - 项目根目录（默认自动推断）
 */
export function genUIDefine(opts = {}) {
    const base = opts.projectPath || projectPath;
    const viewDir = path.resolve(base, opts.viewDir || "assets/view");
    const outputFile = path.resolve(base, opts.outputFile || "src/patch/UIDefine.ts");

    const files = scanFiles(viewDir, ".lh");

    if (files.length === 0) {
        log("未找到 .lh 文件");
        return;
    }

    log(`找到 ${files.length} 个 .lh 文件:`);
    files.forEach(f => console.log(`  ${f}`));

    const propNames = resolvePropNames(files);
    const props = files.map((f, i) => {
        return `    static readonly ${propNames[i]} = "view/${f}";`;
    }).join("\n");

    const classContent = `/** auto generated by tools/genUI.js */
export class UIDefine {
${props}
}`;

    fs.mkdirSync(path.dirname(outputFile), { recursive: true });
    fs.writeFileSync(outputFile, classContent + "\n", "utf-8");
    log(`已生成: ${path.relative(base, outputFile)}`);
}

// 直接运行时执行
if (process.argv[1] && fileURLToPath(import.meta.url) === path.resolve(process.argv[1])) {
    genUIDefine();
    log("执行完成");
}

function log(...str) {
    console.log("[genui]", ...str);
}
